// Generated by CoffeeScript 1.11.1
'use strict';

/**
  * @ngdoc function
  * @name forebassApp.controller:MainCtrl
  * @description
  * # MainCtrl
  * Controller of the forebassApp
 */
var MainCtrl;

MainCtrl = (function() {
  function MainCtrl() {
    this.hola = function() {
      return console.log("Como estan?");
    };
  }

  return MainCtrl;

})();

angular.module('forebassApp').controller('MainCtrl', MainCtrl);
